apiVersion: v1
kind: Service
metadata:
  labels:
    app: axon-scale-demo
  name: axon-scale-demo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: axon-scale-demo
  type: ClusterIP
