apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: axon-scale-demo
      jib: {}
deploy:
  kustomize:
    path: "./.k8s/overlays/monolithic/local"
profiles:
  - name: microservices
    deploy:
      kustomize:
        path: "./.k8s/overlays/microservices/local"
