apiVersion: v1
kind: Service
metadata:
  labels:
    app: axon-scale-command-demo
  name: axon-scale-command-demo
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: axon-scale-command-demo
  type: ClusterIP
