apiVersion: v1
data:
  SERVER_PORT: "8081"
  SPRING_PROFILES_ACTIVE: command
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-command-demo-0.postgres-command.default.svc.cluster.local:5432/axon-scale-demo
  SPRING_DATASOURCE_USERNAME: demouser
  SPRING_DATASOURCE_PASSWORD: thepassword
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON-CONTEXTUAL-CREATION: "true"
  AXON_AXONSERVER_SERVERS: axonserver-0.axonserver.default.svc.cluster.local:8124
kind: ConfigMap
metadata:
  name: axon-scale-command-demo-config
