apiVersion: v1
kind: Service
metadata:
  name: postgres-query
  labels:
    app: postgres-query
spec:
  ports:
    - port: 5432
      name: postgresquery
  clusterIP: None
  selector:
    app: postgres-query
